### ISSUE TITLE
trovare un modo completo per fare il mock di localStorage negli unit test

### ISSUE THREAD

**Issue by AlexRizzus** [GruppOne/stalker-web-app#116]

**Comment by erclu** [comment]
avevi già provato con una cosa così?

https://stackoverflow.com/a/14381941/13323696

**Comment by AlexRizzus** [comment]
yes ma ci sono dei problemi con l'indirizzare gli item usando key che è una stringa che non va molto a genio a typescript, devo approfondire su come sistemare quell'errore
