### ISSUE TITLE
Move JWT token from localStorage to cookie

### ISSUE THREAD

**Issue by AlexRizzus** [GruppOne/stalker-web-app#122]
1. https://www.npmjs.com/package/ngx-cookie-service
2. https://dev.to/gkoniaris/how-to-securely-store-jwt-tokens-51cf
3. https://itnext.io/angular-8-how-to-use-cookies-14ab3f2e93fc

**Comment by erclu** [comment]
un appunto: il primo commento nel tuo secondo link è 

![image](https://user-images.githubusercontent.com/30255227/80863287-703af700-8c7b-11ea-924a-3259bb26e066.png)

link su CSP (content security policy):

https://github.com/GruppOne/stalker-web-app/pull/114#discussion_r418948711
