### ISSUE TITLE
Rifattorizzare inserimento nuovi amministratori

### ISSUE THREAD

**Issue by AlexRizzus** [GruppOne/stalker-web-app#42]

**Comment by erclu** [comment]
link alla discussione: 

https://github.com/GruppOne/stalker-web-app/pull/36/files/3a86cc5f56ca8d10618c9747a84cb4f66465e248#r413159797

**Comment by erclu** [comment]
- [ ] ricordarsi di modificare appropriatamente anche AdminGetType
