### ISSUE TITLE
Configurazione degli ambienti per la web app

### ISSUE THREAD

**Issue by erclu** [GruppOne/stalker-web-app#6]
gli ambienti che mi son venuti in mente sono:

- environment.ts -> mock
- environment.local.ts -> server nostro in localhost (questo environment serve per gli integration test)
- environment.imola.ts -> server di imola remoto + app in localhost (integration test con networking)
- environment.prod.ts -> server remoto TBD + angular online su platform TBD (collaudo)

vanno creati i file .ts e vanno aggiunti alla configurazione angular.json

**Comment by AlexRizzus** [comment]
Mi sembrano sensati, nel mock intendi mettere la web-api di angular che usiamo in locale?
