### ISSUE TITLE
Aggiungere ci per validazione html e css

### ISSUE THREAD

**Issue by erclu** [GruppOne/stalker-web-app#8]
Trovare un modo per eseguire validazione html e css sul sito compilato o attraverso il test runner karma o utilizzando altri servizi online

- [x] validazione css -> attraverso stylelint
- [ ] validazione html -> ?

**Comment by erclu** [comment]
si può fare aggiungendo questo plugin a protractor per quanto riguarda l'html:
https://www.npmjs.com/package/protractor-html-validate

e con un po' di più lavoro usando questo:

https://www.npmjs.com/package/css-validator

e scrivendo un test e2e esplicito

**Comment by fabioscettro** [comment]
Io direi di togliere la necessità di avere un linter di html in modo da chiudere questo issue. Siamo alla fine del progetto e non ne abbiamo ancora trovato uno
